# Built from native speakers, with inspiration from
# https://github.com/zacanger/profane-words
# and
# https://github.com/thisandagain/washyourmouthoutwithsoap/blob/develop/data/build.json
# and
# https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words


english_flagged_words = [
    "anal",
    "bareback",
    "bbw",
    "bdsm",
    "blowjob",
    "blowjobs",
    "brazzers",
    "bukkake",
    "camgirl",
    "camwhore",
    "cocksucking",
    "cougar",
    "creampie",
    "cuckold",
    "cum",
    "cumming",
    "cums",
    "cumshot",
    "cumshots",
    "cumslut",
    "cunnilingus",
    "deepthroat",
    "deepthroating",
    "dildo",
    "dildos",
    "dogging",
    "doggystyle",
    "dominatrix",
    "erotic",
    "fellatio",
    "femdom",
    "fingering",
    "fisting",
    "footjob",
    "gangbang",
    "handjob",
    "hentai",
    "horney",
    "horniest",
    "horny",
    "jism",
    "jizz",
    "masterbating",
    "masturbate",
    "masturbating",
    "masturbation",
    "milf",
    "orgies",
    "orgy",
    "pegging",
    "porn",
    "pornhub",
    "porno",
    "pornos",
    "pornstar",
    "pornstars",
    "redtube",
    "rimming",
    "slutty",
    "squirting",
    "strapon",
    "threesome",
    "vibrator",
    "xhamster",
    "xnxx",
    "xvideos",
    "xxx",
    "youporn",
]


flagged_words = {
    "ar": english_flagged_words
    + [
        "إباحي",
        "احتلام",
        "است",
        "استمناء",
        "اغتصاب",
        "أورغازم",
        "إيروتيك",
        "أير",
        "بز",
        "بزاز",
        "بظر",
        "بورن",
        "بيضان",
        "مص",
        "ثدي",
        "جماع",
        "جنس",
        "حلمة",
        "خلاعة",
        "خنثي",
        "خول",
        "دعارة",
        "زب",
        "سحاق",
        "سحاقية",
        "سكس",
        "سيكس",
        "شاذ",
        "شبق",
        "شرج",
        "شرموطة",
        "شهواني",
        "شهوة",
        "طيز",
        "عادة السرية",
        "عاهرة",
        "عرص",
        "فاسقة",
        "فرج",
        "قحبة",
        "قضيب",
        "كس",
        "لحس",
        "لعق",
        "لواط",
        "لوطي",
        "مؤخرة",
        "متناك",
        "متناكة",
        "مومس",
        "مثير",
        "مص",
        "مضاجعة",
        "مفلقسة",
        "مني",
        "مهتاج",
        "نشوة",
        "نكاح",
        "نيك",
    ],
    "bn": english_flagged_words
    + [
        "আঙ্গুলি করা",
        "আচোদা",
        "খানকি",
        "খানকি মাগি",
        "গান্ড মারানো",
        "গুদ মারানি",
        "চুচুক",
        "চোদ",
        "চোদনা",
        "চোদা",
        "চোদা বোন",
        "চোদাচুদি",
        "জারজ",
        "নাঙ্গ",
        "নেংটা",
        "পর্ণহাব",
        "পর্ন",
        "পর্নস্টার",
        "পর্নোগ্রাফি",
        "পোঁদ",
        "পোঁদ মারানি",
        "পোদ মারানি",
        "বাঁড়া",
        "বানচোদ",
        "বেশ্যা",
        "বেশ্যার ছেলে",
        "বোকাচোদা",
        "ভগ",
        "মা চোদা",
        "মাগী",
        "মাদারচোদ",
        "মুখে নিবি",
        "মোরগ",
        "রেন্ডি",
        "শিশ্ন",
        "স্তন",
        "স্তনবৃন্ত",
        "হস্তমৈথুন",
    ],
    "ca": english_flagged_words
    + [
        "cagarro",
        "cagarros",
        "cipote",
        "cipotes",
        "collons",
        "colló",
        "consolador",
        "consoladors",
        "cony",
        "conys",
        "corre's",
        "corre't",
        "corregut",
        "cunillingus",
        "córrer-se",
        "escorreguda",
        "escorregudes",
        "escorregut",
        "escrot",
        "escrots",
        "escórre's",
        "escórre't",
        "escórrer-se",
        "mamada",
        "mamadera",
        "mamaderes",
        "mamades",
        "masturba",
        "masturbacions",
        "masturbació",
        "masturbant",
        "masturbar",
        "masturbar-se",
        "masturbat",
        "masturbats",
        "masturbes",
        "orgasme",
        "orgasmes",
        "ou",
        "ous",
        "palla",
        "palles",
        "pornografia",
        "semen",
        "semens",
        "verga",
        "vergues",
        "xxx",
    ],
    "en": english_flagged_words,
    "es": english_flagged_words
    + [
        "chupar el coño",
        "chupar la concha",
        "chupar la polla",
        "chupar la verga",
        "comer el coño",
        "comer la concha",
        "comer la polla",
        "comer la verga",
        "coprofagía",
        "correrse",
        "cunillingus",
        "fagging",
        "felación",
        "felching",
        "follada",
        "follador de culo",
        "folladores",
        "fudge packer",
        "hacer una paja",
        "hacerse una paja",
        "hore",
        "kock",
        "macizorra",
        "madre folladora",
        "mamada",
        "perro follador",
        "pisser",
        "pornografía",
        "sado",
        "sadomasoquismo",
        "sadomasoquista",
        "sexo anal",
        "skank",
        "smegma",
        "x clasificado",
    ],
    "eu": english_flagged_words + [],
    "fr": english_flagged_words
    + [
        "baiseurs",
        "baiseur",
        "baiseuse",
        "baiseuses",
        "branlette",
        "branlettes",
        "branleuse",
        "branleuses",
        "cunillingus",
        "cunilingus",
        "enculée",
        "enculées",
        "enculation",
        "enculations",
        "enculement",
        "enculements",
        "fellation",
        "fellations",
        "porno",
        "pornos",
        "pornographie",
        "pornographique",
        "pornographiques",
        "salope",
        "salopes",
        "suceuse",
        "suceuses",
        "xxx",
    ],
    "hi": english_flagged_words
    + [
        "अंडकोश की थैली",
        "एक्स रेटेड",
        "ओगाज़्म",
        "कामोद्दीपक चित्र",
        "कालीन का चूरा",
        "कून",
        "कॉक",
        "गेंद का थैला",
        "चाकलेट का रंग",
        "चूची",
        "चूतड़",
        "झटका बंद",
        "ठगना पैकर",
        "डिल्डो",
        "नितंब",
        "पिछाड़ी",
        "पीड़न कामुक",
        "पॉर्न",
        "फटना",
        "फूहड़",
        "बट",
        "बहुत मदहोश",
        "बेल अंत",
        "भगवान-शापित",
        "भगशेफ",
        "माँ कमीने",
        "मुखमैथुन",
        "मुर्गा चूसने वाला",
        "रक्तरंजित",
        "लेबिया",
        "वहशी",
        "वहशीता",
        "वैंग",
        "शिश्नमल",
        "संभोग सुख",
        "सह शॉट",
        "सींग का बना हुआ",
        "होर",
        "घपा घप",
        "चुदाई",
        "चुदक्कड़",
    ],
    "id": english_flagged_words
    + [
        "bokep",
        "coli",
        "colmek",
        "grepe",
        "horni",
        "janda",
        "jembut",
        "jilat memek",
        "jilmek",
        "kontol",
        "masturbasi",
        "memek",
        "ngentot",
        "ngewe",
        "peju",
        "pepek",
        "pornografi",
        "sange",
        "sepong",
        "tusbol",
    ],
    "pt": english_flagged_words
    + [
        "balalao",
        "bate uma",
        "beijo grego",
        "boceta",
        "boquete",
        "buceta",
        "caralho",
        "chochota",
        "coito",
        "cona",
        "consolo",
        "corno",
        "cu",
        "dar a bunda",
        "dar o rabo",
        "dildo",
        "dildos",
        "esporrar",
        "estrovenga",
        "felação",
        "filho da puta",
        "filhos da puta",
        "gozada",
        "jeba",
        "perereca",
        "pica",
        "piru",
        "porno",
        "pornografia",
        "pornô",
        "porra",
        "prostituta",
        "pube",
        "punheta",
        "punheteiro",
        "putaria",
        "queca",
        "sexo",
        "siririca",
        "tesão",
        "trepada",
        "verga",
        "vibrador",
        "xana",
        "xochota",
        "xoxota",
    ],
    "ur": english_flagged_words
    + [
        "انگلی کرنا",
        "ایکس ریٹیڈ",
        "بلو جاب",
        "بٹ",
        "جھٹکا بند",
        "دلڈو",
        "رنڈی",
        "سلٹ",
        "سکلیرا",
        "سیڈسٹ",
        "سیکس بم",
        "شہوانی",
        "شہوت انگیز",
        "فحش نگاری",
        "لن",
        "لنڈ",
        "لنڈ چوسنے والا",
        "لوڑہ",
        "ماں کمینے",
        "مشت زنی",
        "ممے",
        "مٹھ",
        "مٹھی",
        "ویشیا",
        "پورن",
        "پھدی",
        "پیگنگ",
        "چدائ",
        "چدک",
        "چوت",
        "چودنا",
        "چوچی",
        "کسبی",
        "کسنگ",
        "گانڈ",
        "گدا",
        "ہینڈ جاب",
    ],
    "vi": english_flagged_words
    + [
        "cặc",
        "lồn",
        "địt",
        "buồi",
        "đụ",
        "nứng",
        "phò",
        "bú lol",
        "bú lon",
        "bú cac",
        "bú cak",
        "bú cax",
        "bú buoi",
        "bú mút",
        "húp lol",
        "húp lon",
        "húp sò",
        "nung lol",
        "nung lon",
        "nug lon",
        "nung cac",
        "nung buoi",
        "thèm dit",
        "thèm lon",
        "thèm lol",
        "thèm buoi",
        "thèm dit",
        "thèm chich",
        "thèm chịch",
        "thèm cax",
        "thèm cak",
        "móc lol",
        "móc lon",
        "buscu",
        "lol non",
        "bướm non",
        "vú to",
        "vú bự",
        "lon to",
        "phim sex",
        "phim xex",
        "phim xxx",
    ],
    "zh": english_flagged_words
    + [
        "三级片",
        "乳交",
        "卖B",
        "卖比",
        "卖淫",
        "口交",
        "姣西",
        "打炮",
        "打飞机",
        "抽插",
        "招妓",
        "插你",
        "插死你",
        "淫水",
        "肉壁",
        "肉棍子",
        "肉缝",
        "肏",
        "肛交",
    ],

    "tr": [
        "abaza",
        "abazan",
        "ag",
        "ağzına sıçayım",
        "ahmak",
        "allah",
        "allahsız",
        "am",
        "amarım",
        "ambiti",
        "am biti",
        "amcığı ",
        "amcığın",
        "amcığını",
        "amcığınızı",
        "amcık",
        "amcık hoşafı",
        "amcıklama",
        "amcıklandı",
        "amcik",
        "amck",
        "amckl",
        "amcklama",
        "amcklaryla",
        "amckta",
        "amcktan",
        "amcuk",
        "amık",
        "amına",
        "amınako",
        "amına koy",
        "amına koyarım",
        "amına koyayım",
        "amınakoyim",
        "amına koyyim",
        "amına s",
        "amına sikem",
        "amına sokam",
        "amın feryadı",
        "amını",
        "amını s",
        "amın oglu",
        "amınoğlu",
        "amın oğlu",
        "amısına",
        "amısını",
        "amina",
        "amina g",
        "amina k",
        "aminako",
        "aminakoyarim",
        "amina koyarim",
        "amina koyayım",
        "amina koyayim",
        "aminakoyim",
        "aminda",
        "amindan",
        "amindayken",
        "amini",
        "aminiyarraaniskiim",
        "aminoglu",
        "amin oglu",
        "amiyum",
        "amk",
        "amkafa",
        "amk çocuğu",
        "amlarnzn",
        "amlı",
        "amm",
        "ammak",
        "ammna",
        "amn",
        "amna",
        "amnda",
        "amndaki",
        "amngtn",
        "amnn",
        "amona",
        "amq",
        "amsız",
        "amsiz",
        "amsz",
        "amteri",
        "amugaa",
        "amuğa",
        "amuna",
        "ana",
        "anaaann",
        "anal",
        "analarn",
        "anam",
        "anamla",
        "anan",
        "anana",
        "anandan",
        "ananı",
        "ananı ",
        "ananın",
        "ananın am",
        "ananın amı",
        "ananın dölü",
        "ananınki",
        "ananısikerim",
        "ananı sikerim",
        "ananısikeyim",
        "ananı sikeyim",
        "ananızın",
        "ananızın am",
        "anani",
        "ananin",
        "ananisikerim",
        "anani sikerim",
        "ananisikeyim",
        "anani sikeyim",
        "anann",
        "ananz",
        "anas",
        "anasını",
        "anasının am",
        "anası orospu",
        "anasi",
        "anasinin",
        "anay",
        "anayin",
        "angut",
        "anneni",
        "annenin",
        "annesiz",
        "anuna",
        "aptal",
        "aq",
        "a.q",
        "a.q.",
        "aq.",
        "ass",
        "atkafası",
        "atmık",
        "attırdığım",
        "attrrm",
        "auzlu",
        "avrat",
        "ayklarmalrmsikerim",
        "azdım",
        "azdır",
        "azdırıcı",
        "babaannesi kaşar",
        "babanı",
        "babanın",
        "babani",
        "babası pezevenk",
        "bacağına sıçayım",
        "bacına",
        "bacını",
        "bacının",
        "bacini",
        "bacn",
        "bacndan",
        "bacy",
        "bastard",
        "basur",
        "beyinsiz",
        "bızır",
        "bitch",
        "biting",
        "bok",
        "boka",
        "bokbok",
        "bokça",
        "bokhu",
        "bokkkumu",
        "boklar",
        "boktan",
        "boku",
        "bokubokuna",
        "bokum",
        "bombok",
        "boner",
        "bosalmak",
        "boşalmak",
        "cenabet",
        "cibiliyetsiz",
        "cibilliyetini",
        "cibilliyetsiz",
        "cif",
        "cikar",
        "cim",
        "çük",
        "dalaksız",
        "dallama",
        "daltassak",
        "dalyarak",
        "dalyarrak",
        "dangalak",
        "dassagi",
        "diktim",
        "dildo",
        "dingil",
        "dingilini",
        "dinsiz",
        "dkerim",
        "domal",
        "domalan",
        "domaldı",
        "domaldın",
        "domalık",
        "domalıyor",
        "domalmak",
        "domalmış",
        "domalsın",
        "domalt",
        "domaltarak",
        "domaltıp",
        "domaltır",
        "domaltırım",
        "domaltip",
        "domaltmak",
        "dölü",
        "dönek",
        "düdük",
        "eben",
        "ebeni",
        "ebenin",
        "ebeninki",
        "ebleh",
        "ecdadını",
        "ecdadini",
        "embesil",
        "emi",
        "fahise",
        "fahişe",
        "feriştah",
        "ferre",
        "fuck",
        "fucker",
        "fuckin",
        "fucking",
        "gavad",
        "gavat",
        "geber",
        "geberik",
        "gebermek",
        "gebermiş",
        "gebertir",
        "gerızekalı",
        "gerizekalı",
        "gerizekali",
        "gerzek",
        "giberim",
        "giberler",
        "gibis",
        "gibiş",
        "gibmek",
        "gibtiler",
        "goddamn",
        "godoş",
        "godumun",
        "gotelek",
        "gotlalesi",
        "gotlu",
        "gotten",
        "gotundeki",
        "gotunden",
        "gotune",
        "gotunu",
        "gotveren",
        "goyiim",
        "goyum",
        "goyuyim",
        "goyyim",
        "göt",
        "göt deliği",
        "götelek",
        "göt herif",
        "götlalesi",
        "götlek",
        "götoğlanı",
        "göt oğlanı",
        "götoş",
        "götten",
        "götü",
        "götün",
        "götüne",
        "götünekoyim",
        "götüne koyim",
        "götünü",
        "götveren",
        "göt veren",
        "göt verir",
        "gtelek",
        "gtn",
        "gtnde",
        "gtnden",
        "gtne",
        "gtten",
        "gtveren",
        "hasiktir",
        "hassikome",
        "hassiktir",
        "has siktir",
        "hassittir",
        "haysiyetsiz",
        "hayvan herif",
        "hoşafı",
        "hödük",
        "hsktr",
        "huur",
        "ıbnelık",
        "ibina",
        "ibine",
        "ibinenin",
        "ibne",
        "ibnedir",
        "ibneleri",
        "ibnelik",
        "ibnelri",
        "ibneni",
        "ibnenin",
        "ibnerator",
        "ibnesi",
        "idiot",
        "idiyot",
        "imansz",
        "ipne",
        "iserim",
        "işerim",
        "itoğlu it",
        "kafam girsin",
        "kafasız",
        "kafasiz",
        "kahpe",
        "kahpenin",
        "kahpenin feryadı",
        "kaka",
        "kaltak",
        "kancık",
        "kancik",
        "kappe",
        "karhane",
        "kaşar",
        "kavat",
        "kavatn",
        "kaypak",
        "kayyum",
        "kerane",
        "kerhane",
        "kerhanelerde",
        "kevase",
        "kevaşe",
        "kevvase",
        "koca göt",
        "koduğmun",
        "koduğmunun",
        "kodumun",
        "kodumunun",
        "koduumun",
        "koyarm",
        "koyayım",
        "koyiim",
        "koyiiym",
        "koyim",
        "koyum",
        "koyyim",
        "krar",
        "kukudaym",
        "laciye boyadım",
        "lavuk",
        "liboş",
        "madafaka",
        "mal",
        "malafat",
        "malak",
        "manyak",
        "mcik",
        "meme",
        "memelerini",
        "mezveleli",
        "minaamcık",
        "mincikliyim",
        "mna",
        "monakkoluyum",
        "motherfucker",
        "mudik",
        "oc",
        "ocuu",
        "ocuun",
        "OÇ",
        "oç",
        "o. çocuğu",
        "oğlan",
        "oğlancı",
        "oğlu it",
        "orosbucocuu",
        "orospu",
        "orospucocugu",
        "orospu cocugu",
        "orospu çoc",
        "orospuçocuğu",
        "orospu çocuğu",
        "orospu çocuğudur",
        "orospu çocukları",
        "orospudur",
        "orospular",
        "orospunun",
        "orospunun evladı",
        "orospuydu",
        "orospuyuz",
        "orostoban",
        "orostopol",
        "orrospu",
        "oruspu",
        "oruspuçocuğu",
        "oruspu çocuğu",
        "osbir",
        "ossurduum",
        "ossurmak",
        "ossuruk",
        "osur",
        "osurduu",
        "osuruk",
        "osururum",
        "otuzbir",
        "öküz",
        "öşex",
        "patlak zar",
        "penis",
        "pezevek",
        "pezeven",
        "pezeveng",
        "pezevengi",
        "pezevengin evladı",
        "pezevenk",
        "pezo",
        "pic",
        "pici",
        "picler",
        "piç",
        "piçin oğlu",
        "piç kurusu",
        "piçler",
        "pipi",
        "pipiş",
        "pisliktir",
        "porno",
        "pussy",
        "puşt",
        "puşttur",
        "rahminde",
        "revizyonist",
        "s1kerim",
        "s1kerm",
        "s1krm",
        "sakso",
        "saksofon",
        "salaak",
        "salak",
        "saxo",
        "sekis",
        "serefsiz",
        "sevgi koyarım",
        "sevişelim",
        "sexs",
        "sıçarım",
        "sıçtığım",
        "sıecem",
        "sicarsin",
        "sie",
        "sik",
        "sikdi",
        "sikdiğim",
        "sike",
        "sikecem",
        "sikem",
        "siken",
        "sikenin",
        "siker",
        "sikerim",
        "sikerler",
        "sikersin",
        "sikertir",
        "sikertmek",
        "sikesen",
        "sikesicenin",
        "sikey",
        "sikeydim",
        "sikeyim",
        "sikeym",
        "siki",
        "sikicem",
        "sikici",
        "sikien",
        "sikienler",
        "sikiiim",
        "sikiiimmm",
        "sikiim",
        "sikiir",
        "sikiirken",
        "sikik",
        "sikil",
        "sikildiini",
        "sikilesice",
        "sikilmi",
        "sikilmie",
        "sikilmis",
        "sikilmiş",
        "sikilsin",
        "sikim",
        "sikimde",
        "sikimden",
        "sikime",
        "sikimi",
        "sikimiin",
        "sikimin",
        "sikimle",
        "sikimsonik",
        "sikimtrak",
        "sikin",
        "sikinde",
        "sikinden",
        "sikine",
        "sikini",
        "sikip",
        "sikis",
        "sikisek",
        "sikisen",
        "sikish",
        "sikismis",
        "sikiş",
        "sikişen",
        "sikişme",
        "sikitiin",
        "sikiyim",
        "sikiym",
        "sikiyorum",
        "sikkim",
        "sikko",
        "sikleri",
        "sikleriii",
        "sikli",
        "sikm",
        "sikmek",
        "sikmem",
        "sikmiler",
        "sikmisligim",
        "siksem",
        "sikseydin",
        "sikseyidin",
        "siksin",
        "siksinbaya",
        "siksinler",
        "siksiz",
        "siksok",
        "siksz",
        "sikt",
        "sikti",
        "siktigimin",
        "siktigiminin",
        "siktiğim",
        "siktiğimin",
        "siktiğiminin",
        "siktii",
        "siktiim",
        "siktiimin",
        "siktiiminin",
        "siktiler",
        "siktim",
        "siktim ",
        "siktimin",
        "siktiminin",
        "siktir",
        "siktir et",
        "siktirgit",
        "siktir git",
        "siktirir",
        "siktiririm",
        "siktiriyor",
        "siktir lan",
        "siktirolgit",
        "siktir ol git",
        "sittimin",
        "sittir",
        "skcem",
        "skecem",
        "skem",
        "sker",
        "skerim",
        "skerm",
        "skeyim",
        "skiim",
        "skik",
        "skim",
        "skime",
        "skmek",
        "sksin",
        "sksn",
        "sksz",
        "sktiimin",
        "sktrr",
        "skyim",
        "slaleni",
        "sokam",
        "sokarım",
        "sokarim",
        "sokarm",
        "sokarmkoduumun",
        "sokayım",
        "sokaym",
        "sokiim",
        "soktuğumunun",
        "sokuk",
        "sokum",
        "sokuş",
        "sokuyum",
        "soxum",
        "sulaleni",
        "sülaleni",
        "sülalenizi",
        "sürtük",
        "şerefsiz",
        "şıllık",
        "taaklarn",
        "taaklarna",
        "tarrakimin",
        "tasak",
        "tassak",
        "taşak",
        "taşşak",
        "tipini s.k",
        "tipinizi s.keyim",
        "tiyniyat",
        "toplarm",
        "topsun",
        "totoş",
        "vajina",
        "vajinanı",
        "veled",
        "veledizina",
        "veled i zina",
        "verdiimin",
        "weled",
        "weledizina",
        "whore",
        "xikeyim",
        "yaaraaa",
        "yalama",
        "yalarım",
        "yalarun",
        "yaraaam",
        "yarak",
        "yaraksız",
        "yaraktr",
        "yaram",
        "yaraminbasi",
        "yaramn",
        "yararmorospunun",
        "yarra",
        "yarraaaa",
        "yarraak",
        "yarraam",
        "yarraamı",
        "yarragi",
        "yarragimi",
        "yarragina",
        "yarragindan",
        "yarragm",
        "yarrağ",
        "yarrağım",
        "yarrağımı",
        "yarraimin",
        "yarrak",
        "yarram",
        "yarramin",
        "yarraminbaşı",
        "yarramn",
        "yarran",
        "yarrana",
        "yarrrak",
        "yavak",
        "yavş",
        "yavşak",
        "yavşaktır",
        "yavuşak",
        "yılışık",
        "yilisik",
        "yogurtlayam",
        "yoğurtlayam",
        "yrrak",
        "zıkkımım",
        "zibidi",
        "zigsin",
        "zikeyim",
        "zikiiim",
        "zikiim",
        "zikik",
        "zikim",
        "ziksiiin",
        "ziksiin",
        "zulliyetini",
        "zviyetini",
        "fuck",
        "shit",
        "31",
        ":poop:",
        "18+",
        "30+1",
        "a.ıg",
        "a.q",
        "a.q.",
        "adi",
        "ağzına",
        "ak",
        "akp",
        "al ağzına",
        "am biti",
        "am",
        "mk",
        "amcık",
        "amcıkağız",
        "amcıkları",
        "amed",
        "amıg",
        "amık",
        "amın",
        "amına",
        "amınakoyim",
        "amınoğlu",
        "amina",
        "amini",
        "amk",
        "amk",
        "amk.",
        "amq",
        "anan",
        "ananı",
        "ananızı",
        "anasını avradını",
        "anasını",
        "anlık beğeni",
        "anlık beğeni",
        "aq",
        "aşağılıksın",
        "aşağılıksınız",
        "aşağlık",
        "aşağlıksnız",
        "avradını",
        "b.k",
        "babafingo",
        "bacın",
        "bira",
        "biseksuel",
        "bisekuel",
        "bisexual",
        "bisikiverem",
        "bok",
        "boktan",
        "boşluk",
        "boycot",
        "boycott",
        "boykot",
        "browni",
        "ccc",
        "ccc ccc",
        "ccc incisiker ccc",
        "cccincisikerccc",
        "ccs colgate ccc",
        "cm",
        "coca cola",
        "cola",
        "comma separated list oa.q",
        "çük",
        "dalyarak",
        "dasak",
        "dassak",
        "daşak",
        "daşşak",
        "daşşaksız",
        "dede",
        "desteğinizi",
        "destek",
        "destekk",
        "dinci",
        "domuz yagı",
        "domuz yağı",
        "domuzyagı",
        "durum",
        "ensest",
        "erotik",
        "escinsel",
        "eşcinsel",
        "fahişe",
        "fuck",
        "g*t",
        "g*tü",
        "g*tün",
        "g*tüne",
        "g.t",
        "gasp",
        "gavat",
        "gay",
        "geber",
        "gebersin",
        "gerı zekalıdır",
        "gerizekalı",
        "gerizekalıdır",
        "giren çıkan",
        "godoş",
        "got",
        "gotunu",
        "gotuze",
        "göğüs",
        "göt",
        "götü",
        "götüne",
        "götünü",
        "götünüze",
        "götüyle",
        "götveren",
        "götvern",
        "guat",
        "hack",
        "hasiktir",
        "hasiktr",
        "hastir",
        "haşgerya",
        "haydar",
        "hile",
        "hırsız",
        "i.ne",
        "ibne",
        "ibneler",
        "ibneliği",
        "igrenc",
        "iğrenç",
        "inci siker",
        "incisike",
        "incisiker",
        "ipne",
        "ipneler",
        "iş fırsatı",
        "it",
        "iti",
        "itler",
        "kariyer fırsatı",
        "kavat",
        "kazık",
        "kazik",
        "keriz",
        "kerizler",
        "kıç",
        "kıro",
        "kopegi",
        "kopeği",
        "köpeginin",
        "köpekleşme",
        "kro musunuz",
        "kromusunuz",
        "kuku",
        "lan",
        "lanet",
        "lezle",
        "lezler",
        "mallar",
        "meme",
        "memiş",
        "nah",
        "o ç",
        "o.ç",
        "oç",
        "oç.",
        "okuz",
        "orosbu",
        "orospu",
        "orospucocugu",
        "orospular",
        "oruc",
        "oruç",
        "osuram",
        "otusbir",
        "otuzbir",
        "öküz",
        "penis",
        "pezevenk",
        "pezevenkler",
        "pezo",
        "pic",
        "piç",
        "piçi",
        "piçinin",
        "piçler",
        "pis",
        "pok",
        "pokunu",
        "pompalama",
        "pompalamak",
        "porn",
        "porno",
        "protesto",
        "puşt",
        "putpererst",
        "putperest",
        "pvp",
        "rakı",
        "sex",
        "s.tir",
        "sahtekar",
        "sakso",
        "salak",
        "sana ne",
        "sanane",
        "sçkik",
        "seks",
        "serefsiz",
        "serefsz",
        "serefszler",
        "seviş",
        "sevişmek",
        "sex",
        "sıçmak",
        "sıkerım",
        "sıkm",
        "sıktır",
        "si.çmak",
        "sicmak",
        "sicti",
        "sie",
        "sigara",
        "sik",
        "sikenin",
        "siker",
        "sikerim",
        "sikerler",
        "sikert",
        "sikertirler",
        "sikertmek",
        "sikeyim",
        "sikicem",
        "sikiim",
        "sikik",
        "sikim",
        "sikime",
        "sikimi",
        "sikiş",
        "sikişken",
        "sikişmek",
        "sikm",
        "sikmeyi",
        "siksinler",
        "siktiğim",
        "siktimin",
        "siktin",
        "siktir git",
        "siktir",
        "siktirgit",
        "siktirsin",
        "siqem",
        "sisme",
        "skiym",
        "skm",
        "skrm",
        "sktim",
        "sktir",
        "sktirsin",
        "sktr",
        "sktroradan",
        "sktrsn",
        "snane",
        "sokacak",
        "sokarim",
        "sokayım",
        "sülaleni",
        "şerefsiz",
        "şerefsizler",
        "şerefsizlerin",
        "şerefsizlik",
        "şişme bebek",
        "şişme kadın",
        "şişme manken",
        "şişme",
        "tasak",
        "tassak",
        "taşak",
        "taşşak",
        "tayyip",
        "temasıyla",
        "teror",
        "terör",
        "thumb?",
        "tokmaklama",
        "tokmaklamak",
        "top",
        "transeksuel",
        "transeksüel",
        "travesti",
        "ulan",
        "vagina",
        "vajina",
        "vaşina",
        "verem",
        "vodka",
        "votka",
        "yarak",
        "yark",
        "yarrağım",
        "yarrak",
        "yarrak",
        "yarrakf terms to block",
        "yarramın",
        "yarrk",
        "yarro",
        "yavşak",
        "yavşamak",
        "yrak",
        "yrk",
        "israil",
        "irsail",
        "izrail",
        "israli",
        "ısrayıl",
        "ısraıl",
        "ısrail",
        "israıl",
        "israyil",
        "yaudi",
        "yağudi",
        "yahudi",
        "musevi",
        "dürzü",
        "ebenin",
        "embesil",
        "ezik",
        "fahişe",
        "gavat",
        "gavurun dölü",
        "geri zekalı",
        "gerizekalı",
        "göt",
        "göte",
        "götü",
        "götüne",
        "götünü",
        "hayvan",
        "hıyar",
        "hıyarağası",
        "homo",
        "hödük",
        "ibne",
        "ipne",
        "kahpe",
        "kaltak",
        "kanı bozuk",
        "kazma",
        "kıro",
        "kro",
        "lan",
        "mal",
        "manda",
        "mankafa",
        "manyak",
        "moloz",
        "moron",
        "o.ç.",
        "oç",
        "odun",
        "orospu",
        "öküz",
        "pezevenk",
        "piç",
        "puşt",
        "salak",
        "salak",
        "serefsiz",
        "sik",
        "sik kırığı",
        "sikerler",
        "sikertmek",
        "sikik",
        "sikilmiş",
        "siktir",
        "siktir",
        "sperm",
        "sürtük",
        "sütü bozuk",
        "süzme",
        "şerefsiz",
        "şırfıntı",
        "şirret",
        "taşak",
        "totoş",
        "yarak",
        "yarrak",
        "yosma",
        "bok",
        "aq",
        "a.q.",
        "amk",
        "am",
        "amına",
        "israil",
        "irsail",
        "izrail",
        "israli",
        "ısrayıl",
        "ısraıl",
        "ısrail",
        "israıl",
        "israyil",
        "yaudi",
        "yağudi",
        "yahudi",
        "musevi",
        "dürzü",
        "ebenin",
        "embesil",
        "ezik",
        "fahişe",
        "gavat",
        "gavurun dölü",
        "geri zekalı",
        "gerizekalı",
        "göt",
        "göte",
        "götü",
        "götüne",
        "götünü",
        "hayvan",
        "hıyar",
        "hıyarağası",
        "homo",
        "hödük",
        "ibne",
        "ipne",
        "kahpe",
        "kaltak",
        "kanı bozuk",
        "kazma",
        "kıro",
        "kro",
        "lan",
        "mal",
        "manda",
        "mankafa",
        "manyak",
        "moloz",
        "moron",
        "o.ç.",
        "oç",
        "odun",
        "orospu",
        "öküz",
        "pezevenk",
        "piç",
        "puşt",
        "salak",
        "salak",
        "serefsiz",
        "sik",
        "sik kırığı",
        "sikerler",
        "sikertmek",
        "sikik",
        "sikilmiş",
        "siktir",
        "siktir",
        "sperm",
        "sürtük",
        "sütü bozuk",
        "süzme",
        "şerefsiz",
        "şırfıntı",
        "şirret",
        "taşak",
        "totoş",
        "yarak",
        "yarrak",
        "yosma",
        "bok",
        "aq",
        "a.q.",
        "amk",
        "am",
        "amınadürzü",
        "ebenin",
        "embesil",
        "ezik",
        "fahişe",
        "gavat",
        "gavurun dölü",
        "geri zekalı",
        "lann",
        "len",
        "ulen",
        "lannn",
        "leyn",
        "l.an",
        "gerizekalı",
        "göt",
        "göte",
        "götü",
        "götüne",
        "götsün",
        "piçsin",
        "götsünüz",
        "piçsiniz",
        "götünüze",
        "kıçınız",
        "kıçınıza",
        "götünü",
        "hayvan",
        "hıyar",
        "hıyarağası",
        "homo",
        "hödük",
        "ibne",
        "ipne",
        "kahpe",
        "kaltak",
        "kanı",
        "israil",
        "irsail",
        "izrail",
        "israli",
        "ısrayıl",
        "ısraıl",
        "ısrail",
        "israıl",
        "israyil",
        "yaudi",
        "yağudi",
        "yahudi",
        "musevi bozuk",
        "kazma",
        "kıro",
        "kro",
        "lan",
        "mal",
        "manda",
        "mankafa",
        "manyak",
        "moloz",
        "moron",
        "o.ç.",
        "oç",
        "odun",
        "orospu",
        "öküz",
        "pezevenk",
        "piç",
        "puşt",
        "salak",
        "salak",
        "serefsiz",
        "sik",
        "sik kırığı",
        "sikerler",
        "sikertmek",
        "sikik",
        "sikiim",
        "siktim",
        "sikko",
        "siki",
        "beğen",
        "sikilmiş",
        "siktir",
        "siktir",
        "sperm",
        "sürtük",
        "sütü bozuk",
        "süzme",
        "şerefsiz",
        "şırfıntı",
        "şirret",
        "taşak",
        "totoş",
        "yarak",
        "yarrak",
        "yosma",
        "aq",
        "a.q.",
        "amk",
        "amına",
        "amına koyim",
        "amina",
        "ammına",
        "amna",
        "sikim",
        "sikiym",
        "sikeyim",
        "siktr",
        "kodumun",
        "amık",
        "ulker",
        "ülker",
        "ukler",
        "ükler",
        "ülker",
        "beğenirmisiniz",
        "beğen",
        "hz.muhammed",
        "hz.ömer",
        "din",
        "müslüman",
        "hristiyan",
        "musevi",
        "yahudi",
        "dinsiz",
        "dinsiz",
        "farmasi",
        "oriflame",
        "avon",
        "çalışmak istermisiniz?",
        "sikem",
        "sikim",
        "sikiym",
        "s.iktm",
        "s.ikerim",
        "s.ktir",
        "amg",
        "am.k",
        "a.mk",
        "amık",
        "takip",
        "takip et",
        "kaçırma",
        "fırsat",
        "sayfa",
        "beğen",
        "öl",
        "hanımlar",
        "ev hanımları",
        "bayanlar",
        "ilk yorum",
        "rakı",
        "rak",
        "oruspu",
        "oç",
        "oc",
        "ananın",
        "ananınki",
        "bacının",
        "bacını",
        "babanın",
        "sike",
        "skim",
        "skem",
        "anneni",
        "bacını",
        "babanı",
        "amcık",
        "şerefsiz",
        "piç",
        "piçin oğlu",
        "götoş",
        "amcık hoşafı",
        "amına sokam",
        "amk çocuğu",
        "amın feryadı",
        "amın oğlu",
        "piçler",
        "sikerim",
        "sikeyim",
        "siktiğim",
        "siktiğimin",
        "amını",
        "amına",
        "amınoğlu",
        "amk",
        "zina",
        "edit",
        "ipne",
        "ibne",
        "serefsiz",
        "şerefsiz",
        "piç",
        "piç kurusu",
        "götün",
        "götoş",
        "yarrak",
        "amcik",
        "sıçarım",
        "sıçtığım",
        "aq",
        "a.q",
        "a.q.",
        "aq.",
        "a.g.",
        "ag.",
        "amına k",
        "amina k",
        "amına g",
        "amina g",
        "amını s",
        "amına s",
        "ananı ",
        "babanı",
        "anani",
        "babani",
        "bacını",
        "bacini",
        "ecdadını",
        "ecdadini",
        "sikeyim",
        "sulaleni",
        "sülaleni",
        "dallama",
        "dangalak",
        "aptal",
        "salak",
        "gerızekalı",
        "gerizekali",
        "idiot",
        "idiyot",
        "öküz",
        "angut",
        "dalyarak",
        "sikiyim",
        "sikeyim",
        "sikecem",
        "sikicem",
        "sikerim",
        "siktim ",
        "siktiğim",
        "sikiyorum",
        "sikdiğim",
        "sikem",
        "hödük",
        "düdük",
        "beyinsiz",
        "yalaka",
        "yalama",
        "kafasız",
        "kafasiz",
        "göt herif",
        "hayvan herif",
        "itoğlu it",
        "manyak",
        "cenabet",
        "cibilliyetsiz",
        "götüne",
        "götünü",
        "siktir git",
        "siktirgit",
        "siktir ol git",
        "siktirolgit",
        "siktir",
        "hasiktir",
        "hassiktir",
        "has siktir",
        "dalyarak",
        "dalyarrak",
        "kancık",
        "kancik",
        "kaltak",
        "orospu",
        "oruspu",
        "kaşar",
        "fahişe",
        "fahise",
        "pezevenk",
        "pezo",
        "koca göt",
        "am biti",
        "ambiti",
        "götüne koyim",
        "götünekoyim",
        "amınakoyim",
        "aminakoyim",
        "amına k",
        "amina koyayım",
        "amina koyayim",
        "amına koyarım",
        "aminakoyarim",
        "amina koyarim",
        "ananı sikeyim",
        "anani sikeyim",
        "ananısikeyim",
        "ananisikeyim",
        "anani sikerim",
        "ananı sikerim",
        "ananisikerim",
        "ananısikerim",
        "orospu çocuğu",
        "oruspu çocuğu",
        "amk",
        "amq",
        "sikik",
        "götveren",
        "göt veren",
        "amın oğlu",
        "amin oglu",
        "amın oglu",
        "gavat",
        "kavat",
        "anneni",
        "annenin",
        "ananın",
        "ananin",
        "dalyarak",
        "peygamber",
        "pkk",
        "p kk",
        "terörist",
        "terorist",
        "kürdistan",
        "kurdistan",
        "kadek",
        "kongragel",
        "faşizm",
        "faşist",
        "fasizm",
        "fasist",
        "komünizm",
        "komunist",
        "komonist",
        "komünist",
        "komunizm",
        "ülkücü",
        "sikik",
        "amcık",
        "siktir",
        "sürtük",
        "dhkp",
        "devsol",
        "hizbullah",
        "k.o.ç",
        "k.o.c",
        "piç",
        "pic",
        "sie",
        "oç",
        "yarram",
        "göt",
        "meme",
        "takma",
        "dildo",
        "skcem",
        "skerm",
        "skerim",
        "skecem",
        "orrospu",
        "annesiz",
        "kahpe",
        "kappe",
        "anası orospu",
        "yarak",
        "yaram",
        "ananın amı",
        "babası pezevenk",
        "babası tornacı anası orospu",
        "dalaksız",
        "yaraksız",
        "amlı",
        "s1kerim",
        "s1kerm",
        "s1krm",
        "sikim",
        "oyna",
        "emek server",
        "wslik server",
        "wslik",
        "orospu çocukları",
        "amına",
        "Amın",
    ]
}
